name: Backend Production Deploy

on:
  workflow_dispatch:

jobs:
  cdk-diff:
    runs-on: ubuntu-latest
    steps:
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never"
          actions_comment: false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-west-2"
          APP_NAME: "TseUkGraph"
          AWS_ACCOUNT_ID: "667840932059"
          HOSTED_ZONE_ID: "/hostedzone/Z0002449LIV55BVH86BW"
          HOSTED_ZONE_NAME: "thestoryengine.co.uk."
          MULTI_AZ: "false"
          HASURA_HOSTNAME: "graph.thestoryengine.co.uk"
          ACTIONS_HOSTNAME: "actions.thestoryengine.co.uk"
