
### Create new user
POST http://localhost:3000/api/waitlist
content-type: application/json

{
    "email": "keshawn.kassulke38@ethereal.email",
    "lists": ["launch"],
    "donation": {
        "amount": 20,
        "currency": "GBP"
    }
}


### Confirm
GET https://localhost:3000/api/waitlist/confirm?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Mjg1YjgxOS1mMmFhLTRjNjYtOGYzZC04ZGIzYzdiMTNiYjkiLCJhdWQiOiJ0c2UtZ3JhcGgiLCJpYXQiOjE2MTQyNzA5MjMuNDE5LCJleHAiOjE2MTQyNzI3MjMsImh0dHBzOi8vaGFzdXJhLmlvL2p3dC9jbGFpbXMiOnsieC1oYXN1cmEtYWxsb3dlZC1yb2xlcyI6WyJ1c2VyIl0sIngtaGFzdXJhLWRlZmF1bHQtcm9sZSI6InVzZXIiLCJ4LWhhc3VyYS1lbWFpbC1pZ


### Get stripe payment intent
POST http://localhost:3000/api/donate
content-type: application/json

{
    "waitlistId": "e3fd86e2-d3d4-4cbb-97e8-1b7de6eff61f",
    "email": "jedd@thestoryengine.co.uk",
    "amount": "20"
}

### Get stripe payment intent
POST http://localhost:3000/api/donate/complete
content-type: application/json

{
    "email": "boop@doop.com",
    "waitlistId": "e3fd86e2-d3d4-4cbb-97e8-1b7de6eff61f",
    "intentId": "pi_1IQyZ0DS72lMqlMhLuxDB98A"
}