name: AWS Infra Staging Deploy

on:
  workflow_dispatch:
# on:
#   push:
#     paths:
#       - "infrastructure/**"
#     branches: main

defaults:
  run:
    shell: bash
    working-directory: infrastructure

jobs:
  cdk-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: cdk build
        run: make build
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_args: "--require-approval never"
          actions_comment: true
          working_dir: infrastructure/cdk
        env:
          AWS_REGION: "eu-west-2"
          APP_NAME: "StagingTseUkGraph"
          AWS_ACCOUNT_ID: "667840932059"
          HOSTED_ZONE_ID: "/hostedzone/Z0002449LIV55BVH86BW"
          HOSTED_ZONE_NAME: "thestoryengine.co.uk."
          MULTI_AZ: "false"
          HASURA_HOSTNAME: "staging-graph.thestoryengine.co.uk"
